# Generated by Django 2.2.7 on 2019-11-29 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_Cliente', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(default=False, max_length=30)),
                ('p_apellido', models.CharField(default=False, max_length=50)),
                ('m_apellido', models.CharField(default=False, max_length=50)),
                ('edad', models.IntegerField(default=False)),
                ('email', models.EmailField(max_length=254)),
                ('fecha', models.DateTimeField(auto_now=True, verbose_name='Fecha de registro')),
            ],
            options={
                'verbose_name': 'Cliente',
            },
        ),
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id_Pelicula', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('dia', models.CharField(default=False, max_length=10)),
                ('horario', models.CharField(default=False, max_length=15)),
                ('sala', models.CharField(default=False, max_length=20)),
                ('clasificacion', models.CharField(max_length=5)),
            ],
            options={
                'verbose_name': 'Pelicula',
            },
        ),
        migrations.CreateModel(
            name='Boleto',
            fields=[
                ('id_Boleto', models.AutoField(primary_key=True, serialize=False)),
                ('precio', models.IntegerField(default=False)),
                ('asiento', models.IntegerField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comprar.Cliente')),
                ('pelicula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comprar.Pelicula')),
            ],
            options={
                'unique_together': {('id_Boleto', 'asiento')},
            },
        ),
    ]
